# Generated by Django 3.2.25 on 2024-05-08 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0003_invoice_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_deleted', models.BooleanField(default=False)),
                ('work_order_number', models.CharField(max_length=100)),
                ('agreement_date', models.DateField()),
                ('billing_party', models.CharField(max_length=100)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('site', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('special_instructions', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(default='Confirmed', max_length=20)),
                ('billing_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='fleet.machine')),
                ('resource_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
