# Generated by Django 3.2.25 on 2024-06-16 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
        ('billing', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_deleted', models.BooleanField(default=False)),
                ('work_order_number', models.CharField(max_length=100)),
                ('agreement_date', models.DateField()),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('site', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('special_instructions', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(default='Confirmed', max_length=20)),
                ('billing_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.invoice')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.customer')),
                ('machine', models.ManyToManyField(related_name='machines', to='fleet.Machine')),
                ('resource_details', models.ManyToManyField(related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FitnessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_deleted', models.BooleanField(default=False)),
                ('fuel_consumed_in_litres', models.IntegerField()),
                ('transmission_oil_in_litres', models.IntegerField()),
                ('hydraulic_oil_in_litres', models.IntegerField()),
                ('brake_oil_in_litres', models.IntegerField()),
                ('engine_oil_in_litres', models.IntegerField()),
                ('tyre_condition', models.CharField(max_length=20)),
                ('camera_condition', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working')], max_length=20)),
                ('battery_water_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.machine')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_deleted', models.BooleanField(default=False)),
                ('shift', models.CharField(max_length=20)),
                ('hmr', models.IntegerField()),
                ('num_moves', models.IntegerField()),
                ('overtime', models.IntegerField(default=0)),
                ('cooling_minutes', models.IntegerField(default=0)),
                ('safety_check_shoes', models.BooleanField(default=True)),
                ('safety_check_jacket', models.BooleanField(default=True)),
                ('safety_check_helmet', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL)),
                ('helper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
