# Generated by Django 3.2.25 on 2024-06-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyupdate',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='fitnessreport',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
    ]
