# Generated by Django 3.2.25 on 2024-06-23 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleet', '0001_initial'),
        ('workorder', '0002_auto_20240622_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='resource_details',
        ),
        migrations.CreateModel(
            name='MachineResourceLinkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.machine')),
                ('organisation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='machine_resource_linkage',
            field=models.ManyToManyField(related_name='machine_resource_linkage', to='workorder.MachineResourceLinkage'),
        ),
    ]
