# Generated by Django 3.2.25 on 2024-06-16 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder', '0001_initial'),
        ('accounts', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('part_number', models.CharField(max_length=100, null=True, unique=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('category', models.CharField(choices=[('fuel', 'fuel'), ('mechanical_part', 'mechanical_part'), ('electrical_part', 'electrical_part'), ('lubricant', 'lubricant'), ('other', 'other')], max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('hours_used', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('brand_new', 'brand_new'), ('used', 'used'), ('exhausted', 'exhausted')], default='brand_new', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.machine')),
                ('organisation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation')),
                ('work_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
