# Generated by Django 3.2.25 on 2024-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('invoice_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('unpaid', 'unpaid'), ('underpaid', 'underpaid'), ('overpaid', 'overpaid'), ('fully_paid', 'fully_paid')], default='unpaid', max_length=24)),
                ('payer', models.CharField(blank=True, max_length=24, null=True)),
                ('payee', models.CharField(blank=True, max_length=24, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
