version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "7001:7007"
    env_file:
      - .env  # This line specifies that environment variables should be read from the .env file
    depends_on:
      - db

volumes:
  postgres_data:
