# Generated by Django 3.2.25 on 2024-04-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_expiry_date', models.DateField(blank=True, null=True)),
                ('initial_odometer_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_odometer_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_odometer_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='billing.invoice')),
                ('main_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_driver_contracts', to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('vehicle_number', models.CharField(max_length=56)),
                ('make_name', models.CharField(max_length=56)),
                ('model_name', models.CharField(max_length=56)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('cc', models.IntegerField(blank=True, null=True)),
                ('sub_model_name', models.CharField(blank=True, max_length=56, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=56, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=56, null=True)),
                ('odometer_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('color', models.CharField(blank=True, max_length=56, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('purchased_date', models.DateField(blank=True, null=True)),
                ('product_image', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='product.contract')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='accounts.user')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('reading', models.IntegerField(blank=True, null=True)),
                ('reading_type', models.CharField(choices=[('fuel', 'fuel'), ('odometer', 'odometer')], max_length=24, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_transactions', to='product.contract')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_transactions', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=24)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_issues', to='product.contract')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_issues', to='product.product')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('shift_start_time', models.DateTimeField()),
                ('shift_end_time', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendances', to='product.contract')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_attendances', to='product.product')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_products', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='product.product'),
        ),
        migrations.AddField(
            model_name='contract',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_contracts', to='accounts.user'),
        ),
        migrations.AddField(
            model_name='contract',
            name='support_staffs',
            field=models.ManyToManyField(related_name='support_staff_contracts', to='accounts.User'),
        ),
        migrations.AddField(
            model_name='contract',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_contracts', to='accounts.user'),
        ),
    ]
