# Generated by Django 3.2.25 on 2024-04-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('fitness_certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('fitness_certificate_date', models.DateField()),
                ('fitness_certificate_expiry_date', models.DateField()),
                ('fitness_certificate_remarks', models.TextField(blank=True, null=True)),
                ('fitness_document_links', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('insurance_company', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField()),
                ('insurance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insurance_type', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('machine_number', models.CharField(max_length=100, unique=True)),
                ('engine_number', models.CharField(blank=True, max_length=100, null=True)),
                ('chasis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('make_and_model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('registration_rto_office', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField()),
                ('valid_upto', models.DateField()),
                ('registered_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('account_billing_hirer_company', models.CharField(blank=True, max_length=100, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fitnesses', models.ManyToManyField(blank=True, to='fleet.FitnessDetail')),
                ('insurances', models.ManyToManyField(blank=True, to='fleet.InsuranceDetail')),
                ('locations', models.ManyToManyField(blank=True, to='fleet.LocationDetail')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TyreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('tyre_number', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.DateField()),
                ('meter_reading', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoadTaxDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('road_tax_permit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('road_tax_from_date', models.DateField()),
                ('road_tax_to_date', models.DateField()),
                ('road_tax_remarks', models.TextField(blank=True, null=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RCBookDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('rc_book_number', models.CharField(blank=True, max_length=100, null=True)),
                ('rc_book_from_date', models.DateField()),
                ('rc_book_to_date', models.DateField()),
                ('rc_book_remarks', models.TextField(blank=True, null=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('bill_no', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('total_bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor_name', models.CharField(max_length=100)),
                ('taxable_amount_18_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst_18_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst_18_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('igst_18_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxable_amount_28_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst_28_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst_28_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('igst_28_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PUCDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('puc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('puc_from_date', models.DateField()),
                ('puc_to_date', models.DateField()),
                ('puc_remarks', models.TextField(blank=True, null=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='tyres',
            field=models.ManyToManyField(blank=True, to='fleet.TyreDetail'),
        ),
        migrations.AddField(
            model_name='machine',
            name='vehicle_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.fileobject'),
        ),
        migrations.CreateModel(
            name='LoanDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('purchased_on_loan', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_tenure_from', models.DateField()),
                ('loan_tenure_to', models.DateField()),
                ('installment_date', models.DateField()),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_installments', models.IntegerField(blank=True, null=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleet.machine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
