# Generated by Django 3.2.25 on 2024-05-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_auto_20240504_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandetails',
            name='installment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='loan_tenure_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='loan_tenure_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationdetail',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
