# Generated by Django 3.2.25 on 2024-05-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_fileobject_created_by'),
        ('fleet', '0005_auto_20240508_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancedetail',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.fileobject'),
        ),
    ]
