# Generated by Django 3.2.25 on 2024-05-18 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240518_0538'),
        ('fleet', '0006_insurancedetail_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessdetail',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='insurancedetail',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='loandetails',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='locationdetail',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='machine',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='pucdetail',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='purchasedetails',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='rcbookdetail',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='roadtaxdetail',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='tyredetail',
            name='organisation',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.organisation', verbose_name='Organisation'),
        ),
    ]
