# Generated by Django 3.2.25 on 2024-05-01 08:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='fitnesses',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='insurances',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='tyres',
        ),
        migrations.AddField(
            model_name='fitnessdetail',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fleet.machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurancedetail',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fleet.machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationdetail',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fleet.machine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tyredetail',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fleet.machine'),
            preserve_default=False,
        ),
    ]
