# Generated by Django 3.2.25 on 2024-04-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('is_deleted', models.BooleanField(default=False)),
                ('original_file_name', models.CharField(max_length=100)),
                ('mime_type', models.CharField(max_length=100)),
                ('s3_key', models.CharField(max_length=100)),
                ('s3_bucket', models.CharField(max_length=100)),
                ('size', models.IntegerField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
